# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1HJPSizfkY-Yz9BMCCIP7pu_cV5fKbySG
"""

def majmoe(i):
   sum=0
   while i != 0:
     sum +=i%10
     i//=10
   return sum

def function1(n):
  for I in range (n):
    k=majmoe(i)
    if k==n:
      return k
  return print ("not find")