# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1HJPSizfkY-Yz9BMCCIP7pu_cV5fKbySG
"""

def rect(a,b):
   p=2*(a+b)
   s=a*b
   print(p,s)
   return(p,s)
   k,m=rect(t1,t2)