# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1HJPSizfkY-Yz9BMCCIP7pu_cV5fKbySG
"""

def max_min_count(l):
  l.sort()
  count_min=l.count(l[0])
  count_max=l.count(l[-1])
  return l[-1],count_max,l[0],count_min