# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1HJPSizfkY-Yz9BMCCIP7pu_cV5fKbySG
"""

def maximum3(a,b,c):
   max=a
   if b>max:
     max=b
   if c>max:
     max=c
   return max