# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1HJPSizfkY-Yz9BMCCIP7pu_cV5fKbySG
"""

class person:
    def __init__(self,s,n):
     self.score=s
     self.name=n
     print("hello")
h=person (56,"hasan")

