# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1HJPSizfkY-Yz9BMCCIP7pu_cV5fKbySG
"""

def inputlist():
  l=[]
  k=0
  while 2>1:
    k=int(input())
    if k==5:
       break
    l.append(k)
  return l